
# Generated by CodiumAI

import pytest
import yaml
from yaml.scanner import ScannerError

import pr_agent.algo.utils as utils
from pr_agent.log import get_logger

load_yaml = utils.load_yaml


class TestLoadYaml:
    #  Tests that load_yaml loads a valid YAML string
    def test_load_valid_yaml(self):
        yaml_str = 'name: John Smith\nage: 35'
        expected_output = {'name': 'John Smith', 'age': 35}
        assert load_yaml(yaml_str) == expected_output

    def test_initial_parse_uses_c_safe_loader(self, monkeypatch):
        loader = object()
        calls = []

        def fake_load(text, Loader):
            calls.append((text, Loader))
            return {"name": "John"}

        def fail_safe_load(*args, **kwargs):
            pytest.fail("Python SafeLoader should not run on the successful C-loader path")

        monkeypatch.setattr(utils, "_YAML_C_SAFE_LOADER", loader)
        monkeypatch.setattr(utils.yaml, "load", fake_load)
        monkeypatch.setattr(utils.yaml, "safe_load", fail_safe_load)

        assert load_yaml("name: John") == {"name": "John"}
        assert calls == [("name: John", loader)]

    def test_initial_parse_falls_back_to_python_safe_loader(self, monkeypatch):
        loader = object()
        calls = []

        def fail_c_loader(text, Loader):
            calls.append(("c", text, Loader))
            raise yaml.YAMLError("forced C-loader failure")

        def fake_safe_load(text):
            calls.append(("python", text))
            return {"name": "John"}

        monkeypatch.setattr(utils, "_YAML_C_SAFE_LOADER", loader)
        monkeypatch.setattr(utils.yaml, "load", fail_c_loader)
        monkeypatch.setattr(utils.yaml, "safe_load", fake_safe_load)

        assert load_yaml("name: John") == {"name": "John"}
        assert calls == [
            ("c", "name: John", loader),
            ("python", "name: John"),
        ]

    def test_initial_parse_uses_python_safe_loader_without_c_extension(self, monkeypatch):
        calls = []

        def fake_safe_load(text):
            calls.append(text)
            return {"name": "John"}

        monkeypatch.setattr(utils, "_YAML_C_SAFE_LOADER", None)
        monkeypatch.setattr(utils.yaml, "safe_load", fake_safe_load)

        assert load_yaml("name: John") == {"name": "John"}
        assert calls == ["name: John"]

    @pytest.mark.skipif(utils._YAML_C_SAFE_LOADER is None, reason="LibYAML extension unavailable")
    def test_c_loader_risk_detection_uses_real_c_scanner(self, monkeypatch):
        real_scan = utils.yaml.scan
        calls = []

        def spy_scan(text, Loader):
            calls.append((text, Loader))
            return real_scan(text, Loader=Loader)

        monkeypatch.setattr(utils.yaml, "scan", spy_scan)

        assert utils._has_yaml_c_loader_risk("a: !")
        assert calls == [("a: !", utils._YAML_C_SAFE_LOADER)]

    @pytest.mark.parametrize(
        ("yaml_text", "expected"),
        [
            ("a: !", {"a": None}),
            ("!", {}),
            ("- !", [None]),
            ("a: ! # comment", {"a": None}),
            ("a: ! foo", {"a": "foo"}),
            ("a: !!str foo", {"a": "foo"}),
        ],
    )
    def test_initial_parse_preserves_safe_loader_tag_semantics(self, yaml_text, expected):
        assert load_yaml(yaml_text) == expected

    @pytest.mark.parametrize(
        ("yaml_text", "expected"),
        [
            ("\ufeff\ufefftitle: hello", {"\ufefftitle": "hello"}),
            ("---\n\ufefftitle: hello", {"\ufefftitle": "hello"}),
        ],
    )
    def test_initial_parse_preserves_safe_loader_bom_semantics(self, yaml_text, expected):
        assert load_yaml(yaml_text) == expected

    @pytest.mark.parametrize(
        "yaml_text",
        [
            'a: "!"',
            "a: '!'",
            "a: wow!",
        ],
    )
    def test_c_loader_risk_detection_ignores_scalar_exclamation_marks(self, yaml_text):
        assert not utils._has_yaml_c_loader_risk(yaml_text)

    @pytest.mark.parametrize(
        "yaml_text",
        [
            "a: !",
            "a: !!str foo",
            "{title: !!str, type: [Bug fix]}",
            "{title: !!null, type: [Bug fix]}",
            "{title: !!binary, type: [Bug fix]}",
        ],
    )
    def test_c_loader_risk_detection_routes_yaml_tags(self, yaml_text):
        assert utils._has_yaml_c_loader_risk(yaml_text)

    @pytest.mark.skipif(utils._YAML_C_SAFE_LOADER is None, reason="LibYAML extension unavailable")
    @pytest.mark.parametrize(
        ("yaml_text", "expected"),
        [
            ("{title: Fix?, type: [Bug fix]}", True),
            ("[Fix?]", True),
            ("type: [?,, Bug fix]", True),
            ("{? foo: bar}", True),
            ("{title: value}", False),
            ("title: Fix?", False),
            ('{title: "Fix?"}', False),
            ("code: |\n  if x? y: z", False),
        ],
    )
    def test_flow_question_mark_detection(self, yaml_text, expected):
        assert utils._has_yaml_c_loader_risk(yaml_text) is expected

    def test_flow_question_precheck_skips_scan_without_flow_collection(self, monkeypatch):
        def fail_scan(*args, **kwargs):
            pytest.fail("Block-style question marks should not trigger a YAML token pre-scan")

        monkeypatch.setattr(utils.yaml, "scan", fail_scan)

        assert not utils._has_yaml_c_loader_risk("code: |\n  if x? y: z")

    @pytest.mark.parametrize(
        "yaml_text",
        [
            "title: foo\tbar",
            "a: |#comment\n  value",
            "a: >-#comment\n  value",
            "a: |2+#comment\n  value",
        ],
    )
    def test_initial_parse_routes_text_prechecks_through_existing_repair_path(
        self, monkeypatch, yaml_text
    ):
        calls = []

        def fail_c_loader(*args, **kwargs):
            pytest.fail("C loader should not run for known C/Python parser differences")

        def fail_safe_load(text):
            calls.append(("python", text))
            raise yaml.YAMLError("forced SafeLoader failure")

        def fake_try_fix_yaml(text, **kwargs):
            calls.append(("repair", text))
            return {"repaired": True}

        monkeypatch.setattr(utils, "_YAML_C_SAFE_LOADER", object())
        monkeypatch.setattr(utils.yaml, "load", fail_c_loader)
        monkeypatch.setattr(utils.yaml, "safe_load", fail_safe_load)
        monkeypatch.setattr(utils, "try_fix_yaml", fake_try_fix_yaml)

        assert load_yaml(yaml_text) == {"repaired": True}
        assert calls == [
            ("python", yaml_text),
            ("repair", yaml_text),
        ]

    @pytest.mark.skipif(utils._YAML_C_SAFE_LOADER is None, reason="LibYAML extension unavailable")
    @pytest.mark.parametrize(
        "yaml_text",
        [
            "{title: Fix?, type: [Bug fix]}",
            "type: [?,, Bug fix]",
            "{title: !!str, type: [Bug fix]}",
            "{title: !!null, type: [Bug fix]}",
            "{title: !!binary, type: [Bug fix]}",
            "[" * (utils._YAML_MAX_C_NESTING + 1) + "0" + "]" * (utils._YAML_MAX_C_NESTING + 1),
            "- " * (utils._YAML_MAX_C_NESTING + 1) + "0",
            "-  " * (utils._YAML_MAX_C_NESTING + 1) + "0",
            "? " * (utils._YAML_MAX_C_NESTING + 1) + "a",
        ],
    )
    def test_initial_parse_routes_scanner_compatibility_cases_through_existing_repair_path(
        self, monkeypatch, yaml_text
    ):
        calls = []

        def fail_c_loader(*args, **kwargs):
            pytest.fail("C loader should not run for known C/Python parser differences")

        def fail_safe_load(text):
            calls.append(("python", text))
            raise yaml.YAMLError("forced SafeLoader failure")

        def fake_try_fix_yaml(text, **kwargs):
            calls.append(("repair", text))
            return {"repaired": True}

        monkeypatch.setattr(utils.yaml, "load", fail_c_loader)
        monkeypatch.setattr(utils.yaml, "safe_load", fail_safe_load)
        monkeypatch.setattr(utils, "try_fix_yaml", fake_try_fix_yaml)

        assert load_yaml(yaml_text) == {"repaired": True}
        assert calls == [
            ("python", yaml_text),
            ("repair", yaml_text),
        ]

    def test_nesting_precheck_counts_root_mapping(self, monkeypatch):
        monkeypatch.setattr(utils, "_YAML_MAX_C_NESTING", 3)

        assert not utils._has_yaml_c_loader_risk("[[[0]]]")
        assert utils._has_yaml_c_loader_risk("value: [[[0]]]")

    def test_nesting_precheck_skips_large_flat_documents(self, monkeypatch):
        def fail_scan(*args, **kwargs):
            pytest.fail("Flat documents should not trigger a YAML token pre-scan")

        monkeypatch.setattr(utils.yaml, "scan", fail_scan)
        line_count = utils._YAML_MAX_C_NESTING + 50

        flat_mapping = "\n".join(f"key_{index}: value" for index in range(line_count))
        flat_sequence = "\n".join(f"- item_{index}" for index in range(line_count))

        assert not utils._has_yaml_c_loader_risk(flat_mapping)
        assert not utils._has_yaml_c_loader_risk(flat_sequence)

    def test_excessive_nesting_detection_uses_yaml_tokens(self):
        depth = utils._YAML_MAX_C_NESTING + 1
        nested_mapping = "\n".join(" " * index + "a:" for index in range(depth))
        nested_mapping += "\n" + " " * depth + "value: leaf"
        cr_nested_mapping = "\r".join(" " * index + "a:" for index in range(depth))
        cr_nested_mapping += "\r" + " " * depth + "value: leaf"

        mixed_nesting = "- " * 200 + "[" * 200 + "0" + "]" * 200

        indentless_mapping_sequence = []
        for index in range(utils._YAML_MAX_C_NESTING // 2):
            indent = "  " * index
            indentless_mapping_sequence.extend([f"{indent}a:", f"{indent}- a:"])
        indentless_mapping_sequence.append(
            "  " * (utils._YAML_MAX_C_NESTING // 2) + "value: leaf"
        )
        indentless_mapping_sequence = "\n".join(indentless_mapping_sequence)

        assert utils._has_yaml_c_loader_risk("[" * depth + "0" + "]" * depth)
        assert utils._has_yaml_c_loader_risk("- " * depth + "0")
        assert utils._has_yaml_c_loader_risk("-  " * depth + "0")
        assert utils._has_yaml_c_loader_risk("? " * depth + "a")
        assert utils._has_yaml_c_loader_risk(nested_mapping)
        assert utils._has_yaml_c_loader_risk(cr_nested_mapping)
        for line_break in ("\x85", "\u2028", "\u2029"):
            alternate_nested_mapping = line_break.join(" " * index + "a:" for index in range(depth))
            alternate_nested_mapping += line_break + " " * depth + "value: leaf"
            assert utils._has_yaml_c_loader_risk(alternate_nested_mapping)
        assert utils._has_yaml_c_loader_risk(mixed_nesting)
        assert utils._has_yaml_c_loader_risk(indentless_mapping_sequence)
        assert not utils._has_yaml_c_loader_risk('value: "' + "[" * depth + '"')
        assert not utils._has_yaml_c_loader_risk("code: |\n  " + "- " * depth + "text")

    def test_load_invalid_yaml1(self):
        yaml_str = (
            "PR Analysis:\n"
            "  Main theme: Enhancing the `/describe` command prompt by adding title and description\n"
            "  Type of PR: Enhancement\n"
            "  Relevant tests: No\n"
            "  Focused PR: Yes, the PR is focused on enhancing the `/describe` command prompt.\n"
            "\n"
            "PR Feedback:\n"
            "  General suggestions: The PR seems to be well-structured and focused on a specific "
            "enhancement. However, it would be beneficial to add tests to ensure the new feature "
            "works as expected.\n"
            "  Code feedback:\n"
            "    - relevant file: pr_agent/settings/pr_description_prompts.toml\n"
            "      suggestion: Consider using a more descriptive variable name than 'user' for the "
            "command prompt. A more descriptive name would make the code more readable and "
            "maintainable. [medium]\n"
            '      relevant line: user="""PR Info: aaa\n'
            "  Security concerns: No"
        )
        with pytest.raises(ScannerError):
            yaml.safe_load(yaml_str)

        expected_output = {
            "PR Analysis": {
                "Main theme": "Enhancing the `/describe` command prompt by adding title and description",
                "Type of PR": "Enhancement",
                "Relevant tests": False,
                "Focused PR": "Yes, the PR is focused on enhancing the `/describe` command prompt.",
            },
            "PR Feedback": {
                "General suggestions": (
                    "The PR seems to be well-structured and focused on a specific enhancement. "
                    "However, it would be beneficial to add tests to ensure the new feature works as expected."
                ),
                "Code feedback": [{
                    "relevant file": "pr_agent/settings/pr_description_prompts.toml\n",
                    "suggestion": (
                        "Consider using a more descriptive variable name than 'user' for the command prompt. "
                        "A more descriptive name would make the code more readable and maintainable. [medium]"
                    ),
                    "relevant line": 'user="""PR Info: aaa\n',
                }],
                "Security concerns": False,
            },
        }
        assert load_yaml(yaml_str) == expected_output

    def test_load_invalid_yaml2(self):
        yaml_str = '''\
- relevant file: src/app.py:
  suggestion content: The print statement is outside inside the if __name__ ==: \
'''
        with pytest.raises(ScannerError):
            yaml.safe_load(yaml_str)

        expected_output = [{
            "relevant file": "src/app.py:\n",
            "suggestion content": "The print statement is outside inside the if __name__ ==:",
        }]
        assert load_yaml(yaml_str) == expected_output

    def test_load_yaml_with_illegal_control_character(self):
        # A stray C0 control character (e.g. BACKSPACE, 0x08) can end up in an LLM response - commonly when an
        # upstream diff-pruning step truncates the prompt mid multi-byte character. PyYAML's reader rejects such
        # characters outright with a ReaderError, even though the rest of the document is well-formed YAML.
        yaml_str = 'name: John\x08 Smith\nage: 35'
        expected_output = {'name': 'John Smith', 'age': 35}
        with pytest.raises(yaml.reader.ReaderError):
            yaml.safe_load(yaml_str)
        assert load_yaml(yaml_str) == expected_output

    def test_load_yaml_with_illegal_control_character_and_broken_structure(self):
        # Same as above, but combined with a structural issue that requires the try_fix_yaml fallbacks to run,
        # to make sure the sanitized text is what actually reaches those fallbacks.
        yaml_str = 'relevant line: value\x08: 3\n'
        expected_output = {'relevant line': 'value: 3'}
        assert load_yaml(yaml_str) == expected_output

    def test_load_yaml_does_not_strip_mojibake_repair_range(self):
        # Text that was correctly produced as UTF-8 but got wrongly decoded as latin-1 somewhere upstream turns
        # into "mojibake": multi-byte characters (e.g. Chinese) get split into several bytes that mostly land in
        # the \x7f-\x9f C1 control range. The ninth fallback in try_fix_yaml repairs this by re-encoding as
        # latin-1 and decoding as utf-8. If load_yaml's control-character sanitizer strips \x7f-\x9f, it deletes
        # the very bytes that fallback needs, so this must keep working after the illegal-character fix.
        original = {'suggestion content': '修复空指针异常'}
        mojibake = yaml.safe_dump(original, allow_unicode=True).encode('utf-8').decode('latin-1')
        assert load_yaml(mojibake) == original

    def test_load_yaml_sanitized_to_empty_does_not_return_none_silently(self):
        # When the input consists entirely of illegal control characters, sanitize_yaml_control_chars()
        # strips them all and yaml.safe_load('') returns None without raising — which would skip all
        # fallback/logging and return None to callers that assume a dict. The fix raises ValueError to
        # route through the existing failure path, so at minimum a parse-failure log is emitted.
        captured = []
        sink_id = get_logger().add(lambda msg: captured.append(msg), level="WARNING")
        try:
            result = load_yaml('\x08\x08\x08')
            assert result == {}
            assert any("Initial failure to parse AI prediction" in m for m in captured)
        finally:
            get_logger().remove(sink_id)

    def test_load_yaml_genuinely_empty_input_unaffected(self):
        # Genuinely empty/whitespace input should not trigger the new pre-sanitization emptiness
        # check — it must behave exactly as before, producing no extra warnings.
        captured = []
        sink_id = get_logger().add(lambda msg: captured.append(msg), level="WARNING")
        try:
            result = load_yaml('')
            assert result == {}
            assert not any("Preprocessing/sanitization removed all content" in m for m in captured)
        finally:
            get_logger().remove(sink_id)

    # Tests that a fenced block whose info string is separated by a space
    # (CommonMark allows whitespace after the opening fence) parses the same
    # as the flush form.
    def test_space_before_yaml_info_string(self):
        expected = {"name": "John"}

        assert load_yaml("```yaml\nname: John\n```") == expected
        assert load_yaml("``` yaml\nname: John\n```") == expected
        assert load_yaml("``` yml\nname: John\n```") == expected

    @pytest.mark.parametrize("label", ["YAML", "YML", "Yaml", "yMl"])
    def test_yaml_info_string_is_case_insensitive(self, label):
        assert load_yaml(f"```\t{label}\t\nname: John\n```") == {"name": "John"}

    # A fence labeled with a non-YAML info string (e.g. ```text or ```python)
    # must not be extracted and parsed as a YAML snippet. The old pattern's
    # optional (yaml|yml) group let any info string through, so the body
    # started with the stray label and a plain-scalar body came back as a
    # folded string instead of None.
    def test_non_yaml_info_string_not_parsed_as_yaml_snippet(self):
        assert load_yaml("```text\nhello world\n```") == {}
        assert load_yaml("```python\nname: John\n```") == {}

    # A fenced block that only becomes reachable through the snippet fallback
    # (the initial parse fails because of surrounding text) must be extracted
    # and parsed, not crash on a stale group index.
    def test_snippet_fallback_with_surrounding_text(self):
        expected = {"name": "John"}
        assert load_yaml("prefix text\n```yaml\nname: John\n```") == expected
        assert load_yaml("prefix text\n``` yaml\nname: John\n```") == expected


class TestFenceLabelIsNotStrippedByPrefix:
    def test_key_starting_with_yml_is_not_truncated(self):
        assert load_yaml("yml_config:\n  a: 1") == {"yml_config": {"a": 1}}

    def test_plain_yml_key_survives(self):
        assert load_yaml("yml: true") == {"yml": True}

    def test_list_key_starting_with_yml_survives(self):
        assert load_yaml("ymls:\n  - a") == {"ymls": ["a"]}
