# Generated by CodiumAI

from pr_agent.algo.git_patch_processing import handle_patch_deletions
from pr_agent.algo.types import EDIT_TYPE

"""
Code Analysis

Objective:
The objective of the function is to handle entire file or deletion patches and return the patch after omitting the
deletion hunks.

Inputs:
- patch: a string representing the patch to be handled
- original_file_content_str: a string representing the original content of the file
- new_file_content_str: a string representing the new content of the file
- file_name: a string representing the name of the file

Flow:
- If new_file_content_str is empty, set patch to "File was deleted" and return it
- Otherwise, split patch into lines and omit the deletion hunks using the omit_deletion_hunks function
- If the resulting patch is different from the original patch, log a message and set patch to the new patch
- Return the resulting patch

Outputs:
- A string representing the patch after omitting the deletion hunks

Additional aspects:
- The function uses the settings from the configuration files to determine the verbosity level of the logging messages
- The omit_deletion_hunks function is called to remove the deletion hunks from the patch
- The function handles the case where the new_file_content_str is empty by setting the patch to "File was deleted"
"""


class TestHandlePatchDeletions:
    # Tests that handle_patch_deletions returns the original patch when new_file_content_str is not empty
    def test_handle_patch_deletions_happy_path_new_file_content_exists(self):
        patch = '--- a/file.py\n+++ b/file.py\n@@ -1,2 +1,2 @@\n-foo\n-bar\n+baz\n'
        original_file_content_str = 'foo\nbar\n'
        new_file_content_str = 'foo\nbaz\n'
        file_name = 'file.py'
        assert handle_patch_deletions(patch, original_file_content_str, new_file_content_str,
                                      file_name) == patch.rstrip()

    # Tests that handle_patch_deletions returns 'File was deleted' when new_file_content_str is empty
    def test_handle_patch_deletions_edge_case_new_file_content_empty(self):
        patch = '--- a/file.py\n+++ b/file.py\n@@ -1,2 +1,2 @@\n-foo\n-bar\n'
        original_file_content_str = 'foo\nbar\n'
        new_file_content_str = ''
        file_name = 'file.py'
        assert handle_patch_deletions(patch, original_file_content_str, new_file_content_str,
                                      file_name) is None

    # Tests that handle_patch_deletions returns the original patch when patch and patch_new are equal
    def test_handle_patch_deletions_edge_case_patch_and_patch_new_are_equal(self):
        patch = '--- a/file.py\n+++ b/file.py\n@@ -1,2 +1,2 @@\n-foo\n-bar\n'
        original_file_content_str = 'foo\nbar\n'
        new_file_content_str = 'foo\nbar\n'
        file_name = 'file.py'
        assert handle_patch_deletions(patch, original_file_content_str, new_file_content_str,
                                      file_name).rstrip() == patch.rstrip()

    # Tests that handle_patch_deletions returns the modified patch when patch and patch_new are not equal
    def test_handle_patch_deletions_edge_case_patch_and_patch_new_are_not_equal(self):
        patch = '--- a/file.py\n+++ b/file.py\n@@ -1,2 +1,2 @@\n-foo\n-bar\n'
        original_file_content_str = 'foo\nbar\n'
        new_file_content_str = 'foo\nbaz\n'
        file_name = 'file.py'
        expected_patch = '--- a/file.py\n+++ b/file.py\n@@ -1,2 +1,2 @@\n-foo\n-bar'
        assert handle_patch_deletions(patch, original_file_content_str, new_file_content_str,
                                      file_name) == expected_patch


class TestDeletionOnlyPatchIsNotErased:
    """A file that still exists must never have its whole patch trimmed away.

    omit_deletion_hunks drops every hunk that carries no added line, so a diff made
    only of removals used to reduce to "". Callers cannot tell that apart from "no diff",
    and the compressed path in pr_processing then showed the file only as an empty
    header or an unprocessed name, so the model never saw the removed lines.
    """

    DELETIONS_ONLY = "@@ -1,40 +1,4 @@\n-removed one\n-removed two\n kept"

    def test_deletion_only_patch_survives_for_a_modified_file(self):
        out = handle_patch_deletions(
            self.DELETIONS_ONLY, "old\n", "kept\n", "svc.py", EDIT_TYPE.MODIFIED)
        assert out != ""
        assert "-removed one" in out
        assert "-removed two" in out

    def test_fully_emptied_file_patch_survives_when_edit_type_is_modified(self):
        # The shape from #2682. PR #2683 fixed the line-number converter, but
        # handle_patch_deletions runs first on the compressed path, so the converter
        # never saw this patch and the content was still lost there.
        out = handle_patch_deletions(
            "@@ -1,3 +0,0 @@\n-a\n-b\n-c", "a\nb\nc\n", "", "emptied.py", EDIT_TYPE.MODIFIED)
        assert out != ""
        for line in ("-a", "-b", "-c"):
            assert line in out

    def test_deletion_only_hunk_is_still_omitted_when_another_hunk_survives(self):
        # The token-saving intent is preserved: a deletion-only hunk is still dropped
        # whenever at least one other hunk carries added lines.
        out = handle_patch_deletions(
            "@@ -1,3 +1,1 @@\n-a\n-b\n-c\n@@ -10,2 +8,3 @@\n ctx\n+added",
            "a\nb\nc\n", "ctx\nadded\n", "mixed.py", EDIT_TYPE.MODIFIED)
        assert "+added" in out
        assert "-a" not in out

    def test_genuinely_deleted_file_still_reports_no_patch(self):
        # The real deletion path is untouched: a deleted file returns None.
        out = handle_patch_deletions(
            "@@ -1,3 +0,0 @@\n-a\n-b\n-c", "a\nb\nc\n", "", "gone.py", EDIT_TYPE.DELETED)
        assert out is None
